version: '3'
services:
  node:
    image: node:12.14.0
    user: node
    working_dir: /data
    volumes:
      - ./:/data
    ports:
      - 4000:4000
    command: yarn run start
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.2
    volumes:
      - 'mongoData:/data/db'
volumes:
  mongoData:
